### PR TITLE
Add `only`

### PR DESCRIPTION
**Pull request by mathiasbynens**
See https://github.com/genomejs/gql/issues/4#issuecomment-98523512. Let me know if you’d prefer another approach.

### CODE REVIEW

**Comment by contra** [comment]
I think it would be cleaner to use Array.prototype.every to run through the alleles

**Comment by mathiasbynens** [comment]
Done.

**Comment by mathiasbynens** [comment]
Can haz version bump?

**Comment by contra** [comment]
@mathiasbynens 1.1.0

**Pull request merged**
